;;; -*- Mode:LISP; Package:NEW-MATH; Base:10; Readtable:ZL -*-

(defun bar ()
  (let ((a .5d0)
        (b 1.0d0) (c 2.0d0) (d 5.0d0)
        (e 50d0))
    #+foo(setq a (multiply-double a .25d0)
          b (multiply-double b .25d0)
          c (multiply-double c .25d0)
          d (multiply-double d .25d0)
          e (multiply-double e .25d0))
    (li:break a b c d e)
    (li:break (add-double b b)(add-double c c)(add-double d d)(add-double e e)
              (subtract-double b b)(subtract-double c c)(subtract-double d d)(subtract-double e e)
              (multiply-double b b)(multiply-double c c)(multiply-double d d)(multiply-double e e)
              (divide-double b b)(divide-double c c)(divide-double d d)
              ;(divide-double e e)
              ))
  (loop))
