

;;; This the function definition generated by the window maker.

(DEFUN MAKE-TEST-FRAME ()
  (MAKE-INSTANCE 'TV:BORDERED-CONSTRAINT-FRAME-WITH-SHARED-IO-BUFFER
                 ':PANES
                 '((UNSPECIFIED-PANE-NAME6 TV:WINDOW
                                           :BLINKER-DESELECTED-VISIBILITY
                                           :ON
                                           :BLINKER-FLAVOR
                                           TV:RECTANGULAR-BLINKER
                                           :BLINKER-P
                                           T
                                           :DEEXPOSED-TYPEIN-ACTION
                                           :NORMAL
                                           :DEEXPOSED-TYPEOUT-ACTION
                                           :NORMAL
                                           :LABEL
                                           NIL
                                           :SAVE-BITS
                                           T)
                   (UNSPECIFIED-PANE-NAME4 TV:LISP-LISTENER
                                           :BLINKER-DESELECTED-VISIBILITY
                                           :ON
                                           :BLINKER-FLAVOR
                                           TV:RECTANGULAR-BLINKER
                                           :BLINKER-P
                                           T
                                           :DEEXPOSED-TYPEIN-ACTION
                                           :NORMAL
                                           :DEEXPOSED-TYPEOUT-ACTION
                                           :NORMAL
                                           :LABEL
                                           NIL
                                           :SAVE-BITS
                                           T)
                   (UNSPECIFIED-PANE-NAME2 TV:COMMAND-MENU
                                           :BLINKER-DESELECTED-VISIBILITY
                                           :ON
                                           :BLINKER-FLAVOR
                                           TV:RECTANGULAR-BLINKER
                                           :BLINKER-P
                                           T
                                           :DEEXPOSED-TYPEIN-ACTION
                                           :NORMAL
                                           :DEEXPOSED-TYPEOUT-ACTION
                                           :NORMAL
                                           :LABEL
                                           NIL
                                           :SAVE-BITS
                                           T
                                           :ITEM-LIST
                                           ("you" "have" "to" "change" "me")))
                 ':CONSTRAINTS
                 '((TEST-FRAME (DUMMY-NAME8 UNSPECIFIED-PANE-NAME6)
                               ((DUMMY-NAME8 :HORIZONTAL
                                             (:EVEN)
                                             (UNSPECIFIED-PANE-NAME2 UNSPECIFIED-PANE-NAME4)
                                             ((UNSPECIFIED-PANE-NAME2 0.499012s0))
                                             ((UNSPECIFIED-PANE-NAME4 :EVEN)))
                                (UNSPECIFIED-PANE-NAME6 :EVEN))))))
