;;; -*- Mode:LISP; Package:USER; Readtable:CL; Base:10 -*-

(let ((official
        '(
                 &allow-other-keys
                 &aux
                 &body
                 &environment
                 &key
                 &optional
                 &rest
                 &whole
                 *
                 **
                 ***
                 *applyhook*
                 *break-on-warnings*
                 *debug-io*
                 *default-pathname-defaults*
                 *error-output*
                 *evalhook*
                 *features*
                 *load-verbose*
                 *macroexpand-hook*
                 *modules*
                 *package*
                 *print-array*
                 *print-base*
                 *print-case*
                 *print-circle*
                 *print-escape*
                 *print-gensym*
                 *print-length*
                 *print-level*
                 *print-pretty*
                 *print-radix*
                 *query-io*
                 *random-state*
                 *read-base*
                 *read-default-float-format*
                 *read-suppress*
                 *readtable*
                 *standard-input*
                 *standard-output*
                 *terminal-io*
                 *trace-output*
                 +
                 ++
                 +++
                 -
                 /
                 //
                 ///
                 /=
                 1+
                 1-
                 <
                 <=
                 =
                 >
                 >=
                 abs
                 acons
                 acos
                 acosh
                 adjoin
                 adjust-array
                 adjustable-array-p
                 alpha-char-p
                 alphanumericp
                 and
                 append
                 apply
                 applyhook
                 apropos
                 apropos-list
                 aref
                 array
                 array-dimension
                 array-dimension-limit
                 array-dimensions
                 array-element-type
                 array-has-fill-pointer-p
                 array-in-bounds-p
                 array-rank
                 array-rank-limit
                 array-row-major-index
                 array-total-size
                 array-total-size-limit
                 arrayp
                 ash
                 asin
                 asinh
                 assert
                 assoc
                 assoc-if
                 assoc-if-not
                 atan
                 atanh
                 atom
                 bignum
                 bit
                 bit-and
                 bit-andc1
                 bit-andc2
                 bit-eqv
                 bit-ior
                 bit-nand
                 bit-nor
                 bit-not
                 bit-orc1
                 bit-orc2
                 bit-vector
                 bit-vector-p
                 bit-xor
                 block
                 boole
                 boole-1
                 boole-2
                 boole-and
                 boole-andc1
                 boole-andc2
                 boole-c1
                 boole-c2
                 boole-clr
                 boole-eqv
                 boole-ior
                 boole-nand
                 boole-nor
                 boole-orc1
                 boole-orc2
                 boole-set
                 boole-xor
                 both-case-p
                 boundp
                 break
                 butlast
                 byte
                 byte-position
                 byte-size
                 caaaar
                 caaadr
                 caaar
                 caadar
                 caaddr
                 caadr
                 caar
                 cadaar
                 cadadr
                 cadar
                 caddar
                 cadddr
                 caddr
                 cadr
                 call-arguments-limit
                 car
                 case
                 catch
                 ccase
                 cdaaar
                 cdaadr
                 cdaar
                 cdadar
                 cdaddr
                 cdadr
                 cdar
                 cddaar
                 cddadr
                 cddar
                 cdddar
                 cddddr
                 cdddr
                 cddr
                 cdr
                 ceiling
                 cerror
                 char
                 char-bit
                 char-bits
                 char-bits-limit
                 char-code
                 char-code-limit
                 char-control-bit
                 char-downcase
                 char-equal
                 char-font
                 char-font-limit
                 char-greaterp
                 char-hyper-bit
                 char-int
                 char-lessp
                 char-meta-bit
                 char-name
                 char-not-equal
                 char-not-greaterp
                 char-not-lessp
                 char-super-bit
                 char-upcase
                 char/=
                 char<
                 char<=
                 char=
                 char>
                 char>=
                 character
                 characterp
                 check-type
                 cis
                 clear-input
                 clear-output
                 close
                 clrhash
                 code-char
                 coerce
                 common
                 commonp
                 compilation-speed
                 compile
                 compile-file
                 compiled-function
                 compiled-function-p
                 compiler-let
                 complex
                 complexp
                 concatenate
                 cond
                 conjugate
                 cons
                 consp
                 constantp
                 copy-alist
                 copy-list
                 copy-readtable
                 copy-seq
                 copy-symbol
                 copy-tree
                 cos
                 cosh
                 count
                 count-if
                 count-if-not
                 ctypecase
                 decf
                 declaration
                 declare
                 decode-float
                 decode-universal-time
                 defconstant
                 define-modify-macro
                 define-setf-method
                 defmacro
                 defparameter
                 defsetf
                 defstruct
                 deftype
                 defun
                 defvar
                 delete
                 delete-duplicates
                 delete-file
                 delete-if
                 delete-if-not
                 denominator
                 deposit-field
                 describe
                 digit-char
                 digit-char-p
                 directory
                 directory-namestring
                 disassemble
                 do
                 do*
                 do-all-symbols
                 do-external-symbols
                 do-symbols
                 documentation
                 dolist
                 dotimes
                 double-float
                 double-float-epsilon
                 double-float-negative-epsilon
                 dpb
                 dribble
                 ecase
                 ed
                 eighth
                 elt
                 encode-universal-time
                 endp
                 enough-namestring
                 eq
                 eql
                 equal
                 equalp
                 error
                 etypecase
                 eval
                 eval-when
                 evalhook
                 evenp
                 every
                 exp
                 export
                 expt
                 fboundp
                 fceiling
                 ffloor
                 fifth
                 file-author
                 file-length
                 file-namestring
                 file-position
                 file-write-date
                 fill
                 fill-pointer
                 find
                 find-all-symbols
                 find-if
                 find-if-not
                 find-package
                 find-symbol
                 finish-output
                 first
                 fixnum
                 flet
                 float
                 float-digits
                 float-precision
                 float-radix
                 float-sign
                 floatp
                 floor
                 fmakunbound
                 force-output
                 format
                 fourth
                 fresh-line
                 fround
                 ftruncate
                 ftype
                 funcall
                 function
                 functionp
                 gcd
                 gensym
                 gentemp
                 get
                 get-decoded-time
                 get-dispatch-macro-character
                 get-internal-real-time
                 get-internal-run-time
                 get-macro-character
                 get-output-stream-string
                 get-properties
                 get-setf-method
                 get-setf-method-multiple-value
                 get-universal-time
                 getf
                 gethash
                 go
                 graphic-char-p
                 hash-table
                 hash-table-count
                 hash-table-p
                 host-namestring
                 identity
                 if
                 ignore
                 imagpart
                 import
                 in-package
                 incf
                 inline
                 input-stream-p
                 inspect
                 int-char
                 integer
                 integer-decode-float
                 integer-length
                 integerp
                 intern
                 internal-time-units-per-second
                 intersection
                 isqrt
                 keyword
                 keywordp
                 labels
                 lambda
                 lambda-list-keywords
                 lambda-parameters-limit
                 last
                 lcm
                 ldb
                 ldb-test
                 ldiff
                 least-negative-double-float
                 least-negative-long-float
                 least-negative-short-float
                 least-negative-single-float
                 least-positive-double-float
                 least-positive-long-float
                 least-positive-short-float
                 least-positive-single-float
                 length
                 let
                 let*
                 lisp-implementation-type
                 lisp-implementation-version
                 list
                 list*
                 list-all-packages
                 list-length
                 listen
                 listp
                 load
                 locally
                 log
                 logand
                 logandc1
                 logandc2
                 logbitp
                 logcount
                 logeqv
                 logior
                 lognand
                 lognor
                 lognot
                 logorc1
                 logorc2
                 logtest
                 logxor
                 long-float
                 long-float-epsilon
                 long-float-negative-epsilon
                 long-site-name
                 loop
                 lower-case-p
                 machine-instance
                 machine-type
                 machine-version
                 macro-function
                 macroexpand
                 macroexpand-1
                 macrolet
                 make-array
                 make-broadcast-stream
                 make-char
                 make-concatenated-stream
                 make-dispatch-macro-character
                 make-echo-stream
                 make-hash-table
                 make-list
                 make-package
                 make-pathname
                 make-random-state
                 make-sequence
                 make-string
                 make-string-input-stream
                 make-string-output-stream
                 make-symbol
                 make-synonym-stream
                 make-two-way-stream
                 makunbound
                 map
                 mapc
                 mapcan
                 mapcar
                 mapcon
                 maphash
                 mapl
                 maplist
                 mask-field
                 max
                 member
                 member-if
                 member-if-not
                 merge
                 merge-pathnames
                 min
                 minusp
                 mismatch
                 mod
                 most-negative-double-float
                 most-negative-fixnum
                 most-negative-long-float
                 most-negative-short-float
                 most-negative-single-float
                 most-positive-double-float
                 most-positive-fixnum
                 most-positive-long-float
                 most-positive-short-float
                 most-positive-single-float
                 multiple-value-bind
                 multiple-value-call
                 multiple-value-list
                 multiple-value-prog1
                 multiple-value-setq
                 multiple-values-limit
                 name-char
                 namestring
                 nbutlast
                 nconc
                 nil
                 nintersection
                 ninth
                 not
                 notany
                 notevery
                 notinline
                 nreconc
                 nreverse
                 nset-difference
                 nset-exclusive-or
                 nstring-capitalize
                 nstring-downcase
                 nstring-upcase
                 nsublis
                 nsubst
                 nsubst-if
                 nsubst-if-not
                 nsubstitute
                 nsubstitute-if
                 nsubstitute-if-not
                 nth
                 nthcdr
                 null
                 number
                 numberp
                 numerator
                 nunion
                 oddp
                 open
                 optimize
                 or
                 otherwise
                 output-stream-p
                 package
                 package-name
                 package-nicknames
                 package-shadowing-symbols
                 package-use-list
                 package-used-by-list
                 packagep
                 pairlis
                 parse-integer
                 parse-namestring
                 pathname
                 pathname-device
                 pathname-directory
                 pathname-host
                 pathname-name
                 pathname-type
                 pathname-version
                 pathnamep
                 peek-char
                 phase
                 pi
                 plusp
                 pop
                 position
                 position-if
                 position-if-not
                 pprint
                 prin1
                 prin1-to-string
                 princ
                 princ-to-string
                 print
                 probe-file
                 proclaim
                 prog
                 prog*
                 prog1
                 prog2
                 progn
                 progv
                 provide
                 psetf
                 psetq
                 push
                 pushnew
                 quote
                 random
                 random-state
                 random-state-p
                 rassoc
                 rassoc-if
                 rassoc-if-not
                 ratio
                 rational
                 rationalize
                 rationalp
                 read
                 read-byte
                 read-char
                 read-char-no-hang
                 read-delimited-list
                 read-from-string
                 read-line
                 read-preserving-whitespace
                 readtable
                 readtablep
                 realpart
                 reduce
                 rem
                 remf
                 remhash
                 remove
                 remove-duplicates
                 remove-if
                 remove-if-not
                 remprop
                 rename-file
                 rename-package
                 replace
                 require
                 rest
                 return
                 return-from
                 revappend
                 reverse
                 room
                 rotatef
                 round
                 rplaca
                 rplacd
                 safety
                 satisfies
                 sbit
                 scale-float
                 schar
                 search
                 second
                 sequence
                 set
                 set-char-bit
                 set-difference
                 set-dispatch-macro-character
                 set-exclusive-or
                 set-macro-character
                 set-syntax-from-char
                 setf
                 setq
                 seventh
                 shadow
                 shadowing-import
                 shiftf
                 short-float
                 short-float-epsilon
                 short-float-negative-epsilon
                 short-site-name
                 signed-byte
                 signum
                 simple-array
                 simple-bit-vector
                 simple-bit-vector-p
                 simple-string
                 simple-string-p
                 simple-vector
                 simple-vector-p
                 sin
                 single-float
                 single-float-epsilon
                 single-float-negative-epsilon
                 sinh
                 sixth
                 sleep
                 software-type
                 software-version
                 some
                 sort
                 space
                 special
                 special-form-p
                 speed
                 sqrt
                 stable-sort
                 standard-char
                 standard-char-p
                 step
                 stream
                 stream-element-type
                 streamp
                 string
                 string-capitalize
                 string-char
                 string-char-p
                 string-downcase
                 string-equal
                 string-greaterp
                 string-left-trim
                 string-lessp
                 string-not-equal
                 string-not-greaterp
                 string-not-lessp
                 string-right-trim
                 string-trim
                 string-upcase
                 string/=
                 string<
                 string<=
                 string=
                 string>
                 string>=
                 stringp
                 structure
                 sublis
                 subseq
                 subsetp
                 subst
                 subst-if
                 subst-if-not
                 substitute
                 substitute-if
                 substitute-if-not
                 subtypep
                 svref
                 sxhash
                 symbol
                 symbol-function
                 symbol-name
                 symbol-package
                 symbol-plist
                 symbol-value
                 symbolp
                 t
                 tagbody
                 tailp
                 tan
                 tanh
                 tenth
                 terpri
                 the
                 third
                 throw
                 time
                 trace
                 tree-equal
                 truename
                 truncate
                 type
                 type-of
                 typecase
                 typep
                 unexport
                 unintern
                 union
                 unless
                 unread-char
                 unsigned-byte
                 untrace
                 unuse-package
                 unwind-protect
                 upper-case-p
                 use-package
                 user-homedir-pathname
                 values
                 values-list
                 variable
                 vector
                 vector-pop
                 vector-push
                 vector-push-extend
                 vectorp
                 warn
                 when
                 with-input-from-string
                 with-open-file
                 with-open-stream
                 with-output-to-string
                 write
                 write-byte
                 write-char
                 write-line
                 write-string
                 write-to-string
                 y-or-n-p
                 yes-or-no-p
                 zerop
                 ))

      (lambda (sort (let (l)
                     (do-external-symbols (s (find-package :lisp))
                       (pushnew s l))
                     l)
                   #'alphalessp)))

   (format t "~%In LAMBDA but not in Steele:~{ ~s~}"
           (sort (set-difference lambda official) #'alphalessp))

   (format t "~%In Steele but not in LAMBDA:~{ ~s~}"
           (sort (set-difference official lambda) #'alphalessp)))
