
;Reading at top level in Lisp Listener 1.
;Reading in base 10 in package USER with standard Zetalisp readtable.

(load "jb:k;simulation-sysdef")
#FS::LM-PATHNAME "JB: K; SIMULATION-SYSDEF.LISP#209"
(load-k-system-on-lambda-with-defsystem)
Loading JB: K; NMACROS.QFASL#>
Loading JB: K; LAMBDA-LIST.QFASL#>
Loading JB: K; NEW-SETF.QFASL#>
Reading JB: K; CS-PRIMITIVES.LISP#>
Reading JB: K; LI-IMPORTS.LISP#>
Reading JB: K; LI-FAKES.LISP#>
Reading JB: K; COMPILER-SUPPORT.LISP#>
Reading JB: K; HARDWARE-CONSTANTS.LISP#>
Reading JB: K; INSTRUCTIONS.LISP#>
Reading JB: K; ALU-OPCODES.LISP#>
Reading JB: K; FLOATING-POINT-OPCODES.LISP#>
Reading JB: K; FIRM-DEFINITIONS.LISP#>
Reading JB: K; DATA-TYPES.LISP#>
Loading ORSON: FLEABIT; EXTRA-STUFF.QFASL#>
Loading ORSON: FLEABIT; EXPANDING-VECTOR.QFASL#>
Loading ORSON: FLEABIT; TOP-DEFS.QFASL#>
Loading ORSON: FLEABIT; TOP-UTIL.QFASL#>
Loading ORSON: FLEABIT; PROCESSOR-DEFS.QFASL#>
Loading ORSON: FLEABIT; PRIMOP-DEFS.QFASL#>
Loading ORSON: FLEABIT; PRIMITIVES.QFASL#>
Loading ORSON: FLEABIT; HW-PRIMITIVES.QFASL#>
Loading ORSON: FLEABIT; COMPILER-ENV.QFASL#>
Loading ORSON: FLEABIT; DECL.QFASL#>
Loading ORSON: FLEABIT; REWRITE.QFASL#>
Loading ORSON: FLEABIT; NEW-MACROS.QFASL#>
Loading JB: K; NEW-SETF-MACROS.QFASL#>
Reading JB: K; TYPE-PREDICATES.LISP#>
Loading JB: K; TYPES.QFASL#>
Loading ORSON: FLEABIT; HW-MACROS.QFASL#>
Loading ORSON: FLEABIT; TOP.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; TYPE.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; NODESTUFF.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; NFRONT.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; ALPHA.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; COMPILATORS.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; NODE.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; SIMPLIFY.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; SIMPLIFY-CALL.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; SIMPLIFY-LET.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; SIMPLIFY-Y.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; SIMPLIFIERS.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; PARAM.QFASL#>
Loading ORSON: FLEABIT.FRONT-END; FIXUP.QFASL#>
Loading ORSON: FLEABIT.BACK-END; STRATEGY.QFASL#>
Loading ORSON: FLEABIT.BACK-END; LIVE.QFASL#>
Loading ORSON: FLEABIT.BACK-END; TRACE.QFASL#>
Loading ORSON: FLEABIT.BACK-END; CLOSE-ANALYZE.QFASL#>
Loading ORSON: FLEABIT.GENERATE; EMIT.QFASL#>
Loading ORSON: FLEABIT.GENERATE; REG-ALLOC.QFASL#>
Loading ORSON: FLEABIT.GENERATE; GENERATE.QFASL#>
Loading ORSON: FLEABIT.GENERATE; ASSEM.QFASL#>
Loading ORSON: FLEABIT.GENERATE; DIS.QFASL#>
Loading ORSON: FLEABIT.GENERATE; LINKER.QFASL#>
Load-files-for-compiling
Loading JB: K; K-MACROS.QFASL#>
Reading JB: K; PRIMITIVE-SETF.LISP#>
Reading JB: K; CONVERSIONS.LISP#>
Reading JB: K; GLOBAL-REGISTERS.LISP#>
Reading JB: K; MINI-FASLOAD-OPCODES.LISP#>
Loading JB: K; NEW-FASDUMP.QFASL#>
Loading JB: K; DEFSTRUCT.QFASL#>
Load-files-for-debugging
Reading JB: K; SIMULATION-SYSDEF.LISP#>
