; -*- Mode:LISP; Package:ZWEI; Base:10; Readtable:CL -*-
;;; Lisp Machine mail reader
;;; Compiled flavor methods and initializations only
; ** (c) Copyright 1980 Massachusetts Institute of Technology **

(COMPILE-FLAVOR-METHODS CLICK-REMEMBERING-POP-UP-MENU FILTER-SELECTION-FRAME
                        POP-UP-ZMAIL-MULTIPLE-MENU
                        ZMAIL-UTILITY-FRAME
                        UNIVERSE-DEFINITION-FRAME ZMAIL-FILTER-FRAME ZMAIL-PROFILE-FRAME
                        ZMAIL-FRAME
                        ZMAIL-COMMAND-MENU-PANE
                        ZMAIL-DYNAMIC-MOMENTARY-COMMAND-MENU
                        ZMAIL-MAIN-COMMAND-MENU-PANE ZMAIL-MOMENTARY-COMMAND-MENU
                        ZMAIL-MOMENTARY-MENU ZMAIL-MOUSE-SENSITIVE-MODE-LINE-PANE
                        ZMAIL-OVERLYING-WINDOW  ZMAIL-SUMMARY-SCROLL-WINDOW
                        ZMAIL-SUMMARY-TYPEOUT-WINDOW ZMAIL-TYPEOUT-WINDOW ZMAIL-WINDOW
                        ZMAIL-CHOOSE-VARIABLE-VALUES-PANE ZMAIL-COMMAND-MENU-PANE
                        )

(COMPILE-FLAVOR-METHODS ITS-MAIL-FILE-MIXIN ITS-INBOX-BUFFER
                        BABYL-MAIL-FILE-BUFFER RMAIL-FILE-BUFFER
                        TENEX-MAIL-FILE-MIXIN TENEX-INBOX-BUFFER TENEX-MAIL-FILE-BUFFER
                        UNIX-MAIL-FILE-MIXIN UNIX-INBOX-BUFFER UNIX-MAIL-FILE-BUFFER
                        TEXT-MAIL-FILE-BUFFER TEMP-ZMAIL-BUFFER
                        VMS-MAIL-FILE-BUFFER VMS-INBOX-BUFFER)

(COMPILE-FLAVOR-METHODS DRAFT-MSG ZMAIL-SENDING-INTERVAL ZMAIL-PROFILE-BUFFER)

(DEFWINDOW-RESOURCE ZMAIL-MOMENTARY-MENU ()
  :MAKE-WINDOW (ZMAIL-MOMENTARY-MENU)
  :REUSABLE-WHEN :DEEXPOSED)

(DEFWINDOW-RESOURCE ZMAIL-MOMENTARY-COMMAND-MENU ()
  :MAKE-WINDOW (ZMAIL-MOMENTARY-COMMAND-MENU)
  :REUSABLE-WHEN :DEEXPOSED)

(DEFWINDOW-RESOURCE POP-UP-ZMAIL-MULTIPLE-MENU ()
  :MAKE-WINDOW (POP-UP-ZMAIL-MULTIPLE-MENU)
  :REUSABLE-WHEN :DEEXPOSED)

(ADD-INITIALIZATION 'INITIALIZE-ZMAIL '(INITIALIZE-ZMAIL) '(:ONCE))
