package K defined by SIMULATION-PACKAGES and DEF-CORR-PKG
GLOBAL:SETF redefined by K;NEW-SETF
SYMBOL:GETF defined by K;LI-FAKES redefined by K;NEW-SETF-MACROS
PRIMITIVE-SETF exports DECF,INCF in PRIMITIVES conflict with LI
DEFSTRUCT defined by LI-FAKES redefined by DEFSTRUCT
DEBUG-SLOT defined by LAMBDA-DIAG;LMI-DEBUG-METHODS redefined by KBUG;DEBUG-BOARD
MAP-STATUS-VALUES by KBUG and KBUG2
SAVING-CURRENT-K-PC by KBUG;DEBUG-SUPPORT and KBUG2;KBUG-GENERIC
